services:
  beef:
    container_name: beef
    extra_hosts:
      - beef.local:127.0.0.1
    image: ros/beef
    build: .
    ports:
      - 127.0.0.1:3000:3000
    restart: unless-stopped
    volumes:
      - ./config.yaml:/beef/config.yaml
      - ./droppers:/beef/extensions/demos/html/droppers/
  juice-shop:
    container_name: juice-shop
    image: bkimminich/juice-shop
    ports:
      - 127.0.0.1:3500:3000
    environment:
      - NODE_ENV=quiet
    restart: unless-stopped
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "8088:8088"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
volumes:
  caddy_data:
  caddy_config:


